In [1]:
from PIL import Image

import torch
import torch.nn.functional as F
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
eas = np.load('data/syn/easy.npy')
eas.shape

(128, 128, 20)

In [6]:
from src.siren.dataio import get_mgrid
from src.utils import prepare_inputs
from argparse import Namespace
config = Namespace(device='cpu', dataset='easysyn')
data_np, n_reps = prepare_inputs(config)
phi = torch.zeros((20, 128, 128, 2))
grid = get_mgrid(data_np[0].shape, dim=len(data_np.shape) - 1).view(phi.shape[1:])

In [10]:
coords = phi + grid

In [16]:
out = n_reps[0]({'coords':coords[0]})

In [18]:
out['model_in'].shape, out['model_out'].shape

(torch.Size([128, 128, 2]), torch.Size([128, 128, 1]))

In [20]:
out['model_out'].min(), out['model_out'].max()

(tensor(-1.0244, grad_fn=<MinBackward1>),
 tensor(5.0177, grad_fn=<MaxBackward1>))

In [ ]:
grid.view(128, 128, -1).shape

torch.Size([128, 128, 2])

In [ ]:
from src.losses import JacboianDet

phi = np.array([[[1, 0], [0, 2]], [[0, 0], [1, 0]]])
phi = np.expand_dims(phi, axis=0)
phi2 = np.random.randint(0, 2, (10, 10, 2))
grad = np.gradient(phi2.squeeze())
dx = phi[:, 1:, :-1, :] - phi[:, :-1, :-1, :]
dy = phi[:, :-1, 1:, :] - phi[:, :-1, :-1, :]

det = dx[:, :, :, 0] * dy[:, :, :, 1] - dx[:, :, :, 1] * dy[:, :, :, 0]

In [56]:
grad[0].shape, grad[1].shape, grad[2].shape

((10, 10, 2), (10, 10, 2), (10, 10, 2))

In [39]:
phi[:, 1:, :-1, :], phi[:, :-1, :-1, :]

(array([[[[0, 0]]]]), array([[[[1, 0]]]]))

In [36]:
dx, dy, det, dx.shape, dy.shape, det.shape

(array([[[[-1,  0]]]]),
 array([[[[-1,  2]]]]),
 array([[[-2]]]),
 (1, 1, 1, 2),
 (1, 1, 1, 2),
 (1, 1, 1))